spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PWD}
    driver-class-name: oracle.jdbc.OracleDriver
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl_auto: validate
        format_sql: true
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: ${TOKEN_SECRET}