spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: oracle.jdbc.OracleDriver
  config:
    import: optional:secrets.yml
  flyway:
      baseline-on-migrate: true

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    # Hibernate ddl auto
    hibernate:
      ddl-auto: none
server:
  error:
    include-stacktrace: never