spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: oracle.jdbc.OracleDriver
  config:
    import: optional:secrets.yml
  flyway:
    baseline-on-migrate: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        ddl_auto: validate
        format_sql: true
server:
  error:
    include-stacktrace: never
api:
  security:
    token:
      secret: